# .github/workflows/docker-compose-ci.yml

name: CI Workflow with Docker Compose

# Trigger events
on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch
  workflow_dispatch: # Allow manual workflow execution

jobs:
  build-and-test:
    name: Build and Test with Docker Compose
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose and database
      - name: Start Docker Compose
        run: |
          docker-compose -f todo/docker-compose.yml up -d
          echo "Waiting for database to be ready..."
          until docker exec db pg_isready -U user -d testdb; do
            echo "Database not ready, retrying in 5 seconds..."
            sleep 5
          done
          echo "Database is ready."

      # Step 3: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 4: Set executable permissions for Gradle
      - name: Set Gradle executable permissions
        run: |
          cd todo
          chmod +x gradlew

      # Step 5: Build and Test the project
      - name: Build and Test with Gradle
        run: |
          cd todo
          ./gradlew clean build

      # Step 6: Tear down Docker Compose services
      - name: Tear down Docker Compose services
        if: always()
        run: |
          docker-compose -f todo/docker-compose.yml down
