# .github/workflows/gradle-ci.yml

name: CI Workflow

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Without Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Navigate to the todo directory and set permissions
      - name: Set executable permissions
        run: |
          cd todo
          chmod +x gradlew

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('todo/**/*.gradle*', 'todo/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Build the project
      - name: Build with Gradle
        run: |
          cd todo
          ./gradlew clean bootJar -x test

      # Step 6: Verify the JAR file
      - name: Verify JAR file exists
        run: |
          cd todo/build/libs
          ls -la

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Deploy the application
      - name: Deploy application
        run: |
          cd todo
          java -jar build/libs/todo-0.0.1-SNAPSHOT.jar
          echo "Application successfully deployed."
