name: CI with Docker Compose

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose (for Docker Compose V1)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # (Alternative for Docker Compose V2)
      # - name: Docker info
      #   run: |
      #     docker version
      #     docker compose version  # Confirm 'docker compose' is available

      # Step 3: Spin up services via Docker Compose
      - name: Start Docker Compose
        run: |
          docker-compose -f todo/docker-compose.yml up -d
          echo "Waiting a few seconds for services to be ready..."
          sleep 10

      # Step 4: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 5: Make Gradle wrapper executable
      - name: Make gradlew executable
        run: |
          cd todo
          chmod +x gradlew

      # Step 6: Build (and optionally test) the project
      - name: Build project
        run: |
          cd todo
          ./gradlew clean build

      # Step 7: Tear down services
      - name: Tear down Docker Compose services
        if: always()
        run: |
          docker-compose -f todo/docker-compose.yml down
