# .github/workflows/gradle-ci.yml
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Without Database Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Set executable permissions
      - name: Set executable permissions
        run: |
          cd todo
          chmod +x gradlew

      # Step 4: Build and Test
      - name: Build and Test (No Database)
        run: |
          cd todo
          ./gradlew clean test -Dspring.profiles.active=ci
